export const QUOTES: string[] = [
  "“A bad plan is infinitely better than no plan at all” – Garry Kasparov",
  "“A language that doesn’t affect the way you think about programming is not worth knowing” – Alan Perlis",
  "“A sacrifice is best refuted by accepting it” – Wilhelm Steinitz",
  "“Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live” – John Woods",
  "“Am I a man who dreamt of being a butterfly, or a butterfly dreaming of being a man?” – Zhuangzi",
  "“Any fool can write code that a computer can understand, good programmers write code that humans can understand” – Martin Fowler",
  "“Code is like humor. When you have to explain it, it’s bad” – Cory House",
  "“Deleted code is debugged code” – Jeff Sickel",
  "“Even a poor plan is better than no plan at all” – Mikhail Chigorin",
  "“Every commit is a promise to your future self” – Unknown",
  "“First, solve the problem. Then, write the code” – John Johnson",
  "“I don’t believe in psychology. I believe in good moves” – Bobby Fischer",
  "“I’d rather write programs to write programs than write programs” – Dick Sites",
  "“If you can’t explain it simply, you don’t understand it well enough” – Albert Einstein",
  "“In programming, the hard part isn’t solving problems, but deciding what problems to solve” – Paul Graham",
  "“In theory, there is no difference between theory and practice. In practice, there is” – Yogi Berra",
  "“It works on my machine” – Every developer ever",
  "“It’s not a bug, it’s a feature” – Every developer ever",
  "“Make it work, make it right, make it fast” – Kent Beck",
  "“Measuring programming progress by lines of code is like measuring aircraft building progress by weight” – Bill Gates",
  "“99 little bugs in the code, 99 little bugs. Take one down, patch it around, 127 little bugs in the code” – Unknown",
  "“One bad move nullifies forty good ones” – Bernhard Horwitz",
  "“Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away” – Antoine de Saint-Exupéry",
  "“Programs must be written for people to read, and only incidentally for machines to execute” – Harold Abelson",
  "“Real programmers don’t comment their code. If it was hard to write, it should be hard to read” – Unknown",
  "“Simplicity is prerequisite for reliability” – Edsger Dijkstra",
  "“Some people, when confronted with a problem, think “I know, I’ll use regular expressions”. Now they have two problems” – Jamie Zawinski",
  "“Some sacrifices are sound; the rest are mine” – Mikhail Tal",
  "“Tactics is knowing what to do when there is something to do; strategy is knowing what to do when there is nothing to do” – Savielly Tartakower",
  "“Talk is cheap. Show me the code” – Linus Torvalds",
  "“Tell your friends at the bar and the library about it” – agadmator",
  "“The beauty of a move lies not in its appearance but in the thought behind it” – Aron Nimzowitsch",
  "“The best code is no code at all” – Jeff Atwood",
  "“The best error message is the one that never shows up” – Thomas Fuchs",
  "“The best time to plant a tree was 20 years ago. The second best time is now. Same goes for refactoring” – Unknown",
  "“The blunders are all there on the board, waiting to be made” – Savielly Tartakower",
  "“The code works, don’t ask me why” – Every developer ever",
  "“The hardest bug to find is the one you’re sure isn’t there” – Unknown",
  "“The most dangerous phrase in the language is ‘we’ve always done it this way’” – Grace Hopper",
  "“The obstacle is the way” – Marcus Aurelius",
  "“The only way to get smarter is by playing a smarter opponent” – Fundamentals of Chess",
  "“The pin is mightier than the sword” – Fred Reinfeld",
  "“The threat is stronger than the execution” – Aron Nimzowitsch",
  "“The winner of the game is the player who makes the next-to-last mistake” – Savielly Tartakower",
  "“There are only two hard things in computer science: cache invalidation and naming things” – Phil Karlton",
  "“There’s nothing more permanent than a temporary hack” – Kyle Simpson",
  "“To iterate is human, to recurse divine” – L. Peter Deutsch",
  "“Walking on water and developing software from a specification are easy if both are frozen” – Edward V. Berard",
  "“Weeks of coding can save you hours of planning” – Unknown",
  "“When in doubt, play chess” – Tevis",
  "“When you see a good move, look for a better one” – Emanuel Lasker",
  "“You may learn much more from a game you lose than from a game you win” – José Raúl Capablanca",
  "“You must take your opponent into a deep dark forest where 2+2=5, and the path leading out is only wide enough for one” – Mikhail Tal",
];

export function getRandomQuote(): string {
  return QUOTES[Math.floor(Math.random() * QUOTES.length)];
}
